# Name
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1/springcloud_mart?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

# Eureka Address
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000